/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itc_ts8209a_drive_SerialPort */

#ifndef _Included_com_itc_ts8209a_drive_SerialPort
#define _Included_com_itc_ts8209a_drive_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
#undef com_itc_ts8209a_drive_SerialPort_BAUD_9600_
#define com_itc_ts8209a_drive_SerialPort_BAUD_9600_ 9600L
#undef com_itc_ts8209a_drive_SerialPort_BAUD_57600_
#define com_itc_ts8209a_drive_SerialPort_BAUD_57600_ 57600L
#undef com_itc_ts8209a_drive_SerialPort_BAUD_115200_
#define com_itc_ts8209a_drive_SerialPort_BAUD_115200_ 115200L
/*
 * Class:     com_itc_ts8209a_drive_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_itc_ts8209a_drive_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_itc_ts8209a_drive_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itc_ts8209a_drive_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
