/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itc_ts8209a_drive_Ra8876l */

#ifndef _Included_com_itc_ts8209a_drive_Ra8876l
#define _Included_com_itc_ts8209a_drive_Ra8876l
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itc_ts8209a_drive_Ra8876l
 * Method:    sendData
 * Signature: (SSSS[BI)V
 */
JNIEXPORT void JNICALL Java_com_itc_ts8209a_drive_Ra8876l_sendData
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort, jbyteArray, jint);

/*
 * Class:     com_itc_ts8209a_drive_Ra8876l
 * Method:    handShake
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itc_ts8209a_drive_Ra8876l_handShake
  (JNIEnv *, jclass);

/*
 * Class:     com_itc_ts8209a_drive_Ra8876l
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_itc_ts8209a_drive_Ra8876l_init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_itc_ts8209a_drive_Ra8876l
 * Method:    displayOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itc_ts8209a_drive_Ra8876l_displayOn
  (JNIEnv *, jclass);

/*
 * Class:     com_itc_ts8209a_drive_Ra8876l
 * Method:    displayOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itc_ts8209a_drive_Ra8876l_displayOff
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
