/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jackie_ts8209a_Drive_RA8876L */

#ifndef _Included_com_jackie_ts8209a_Drive_RA8876L
#define _Included_com_jackie_ts8209a_Drive_RA8876L
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jackie_ts8209a_Drive_RA8876L
 * Method:    sendData
 * Signature: (SSSS[BI)V
 */
JNIEXPORT void JNICALL Java_com_jackie_ts8209a_Drive_RA8876L_sendData
  (JNIEnv *, jclass, jshort, jshort, jshort, jshort, jbyteArray, jint);

/*
 * Class:     com_jackie_ts8209a_Drive_RA8876L
 * Method:    handShake
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jackie_ts8209a_Drive_RA8876L_handShake
  (JNIEnv *, jclass);

/*
 * Class:     com_jackie_ts8209a_Drive_RA8876L
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jackie_ts8209a_Drive_RA8876L_init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_jackie_ts8209a_Drive_RA8876L
 * Method:    displayOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jackie_ts8209a_Drive_RA8876L_displayOn
  (JNIEnv *, jclass);

/*
 * Class:     com_jackie_ts8209a_Drive_RA8876L
 * Method:    displayOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jackie_ts8209a_Drive_RA8876L_displayOff
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
